In [1]:
import pandas as pd
import numpy as np
from meal_plan_env import DayPlan

In [2]:
num_reqs_df = pd.read_csv("C:/Users/J/Fitness/Meal Plans/num_reqs_df.csv")

In [3]:
pl = DayPlan()

In [4]:
pl.reset()

In [5]:
pl.set_num_reqs(num_reqs_df)

#### 1. Making First Step

In [ ]:
# 

In [6]:
z = np.zeros(len(pl.df))
z[np.random.choice(range(len(pl.df)))] =1

In [7]:
np.where(z==1)[0][0]

166479

In [8]:
pl.df.iloc[np.where(z==1)[0][0],:]

food_key                              401176
food_description     Meatless Chicken Slices
brand                 Worthington Loma Linda
food_type_grp                        grocery
source                            fat_secret
ingredients_list                           0
serving_size_raw              3 slices (57g)
serving_size_val                           3
serving_size_unit               slices (57g)
calories                                  90
protein_g                                  9
fat_g                                    4.5
saturated_fat_g                            1
carb_g                                     2
fiber_g                                    0
sugar_g                                    0
sodium_mg                                250
cholesterol_mg                             0
calcium_mg                               250
iron_mg                                  1.8
vit_a_mcg                                  0
vit_c_mg                                   0
Name: 1664

In [9]:
pl.df[list(map(bool, list(z)))]

food_key         food_description                   brand  \
166479    401176  Meatless Chicken Slices  Worthington Loma Linda   

       food_type_grp      source ingredients_list serving_size_raw  \
166479       grocery  fat_secret                0   3 slices (57g)   

        serving_size_val serving_size_unit  calories    ...     \
166479               3.0      slices (57g)      90.0    ...      

        saturated_fat_g  carb_g  fiber_g  sugar_g  sodium_mg  cholesterol_mg  \
166479              1.0     2.0      0.0      0.0      250.0             0.0   

        calcium_mg  iron_mg  vit_a_mcg  vit_c_mg  
166479       250.0      1.8        0.0       0.0  

[1 rows x 22 columns]

In [10]:
s,r,d =  pl.step(z)

In [11]:
pl.plan_df

food_key         food_description                   brand food_type_grp  \
0  401176.0  Meatless Chicken Slices  Worthington Loma Linda       grocery   

       source ingredients_list serving_size_raw  serving_size_val  \
0  fat_secret                0   3 slices (57g)               3.0   

  serving_size_unit  calories    ...     saturated_fat_g  carb_g  fiber_g  \
0      slices (57g)      90.0    ...                 1.0     2.0      0.0   

   sugar_g  sodium_mg  cholesterol_mg  calcium_mg  iron_mg  vit_a_mcg  \
0      0.0      250.0             0.0       250.0      1.8        0.0   

   vit_c_mg  
0       0.0  

[1 rows x 22 columns]

In [14]:
d

False

#### 2. Making Additional Step

In [15]:
z = np.zeros(len(pl.df))
z[np.random.choice(range(len(pl.df)))] =1

In [16]:
s,r,d =  pl.step(z)

In [22]:
pl.plan_df

food_key                             food_description  \
0  401176.0                      Meatless Chicken Slices   
1   47454.0  CREAMETTE, ENRICHED MACARONI PRODUCT, ZITI,   

                     brand food_type_grp        source  \
0   Worthington Loma Linda       grocery    fat_secret   
1  New World Pasta Company       grocery  usda_branded   

                                    ingredients_list serving_size_raw  \
0                                                  0   3 slices (57g)   
1  SEMOLINA (WHEAT), DURUM FLOUR (WHEAT), NIACIN,...         cup 56g'   

   serving_size_val serving_size_unit  calories    ...     saturated_fat_g  \
0               3.0      slices (57g)      90.0    ...                 1.0   
1               1.0          cup 56g'     200.0    ...                 0.0   

   carb_g  fiber_g  sugar_g  sodium_mg  cholesterol_mg  calcium_mg  iron_mg  \
0     2.0      0.0      0.0      250.0             0.0       250.0      1.8   
1    42.0      2.0      1.0        0.0             0.0         0.0      4.5   

   vit_a_mcg  vit_c_mg  
0        0.0       0.0  
1        0.0       0.0  

[2 rows x 22 columns]

In [28]:
pl.agg_pl

calories  protein_g  fat_g  saturated_fat_g  carb_g  fiber_g  sugar_g  \
0     290.0       16.0    5.5              1.0    44.0      2.0      1.0   

   sodium_mg  cholesterol_mg  calcium_mg  iron_mg  vit_a_mcg  vit_c_mg  
0      250.0             0.0       250.0      6.3        0.0       0.0

In [31]:
pl.thr_mat

array([[   12.36765685,  2400.        ,   300.        ]])

In [32]:
pl.req_mat

array([[   31.16649526,  1000.        ,    18.        ,  5000.        ,
           60.        ]])

In [34]:
pl.mac_mat

array([[ 222.6178233 ,  139.1361396 ,   86.57359795]])

In [35]:
pl.agg_pl

calories  protein_g  fat_g  saturated_fat_g  carb_g  fiber_g  sugar_g  \
0     290.0       16.0    5.5              1.0    44.0      2.0      1.0   

   sodium_mg  cholesterol_mg  calcium_mg  iron_mg  vit_a_mcg  vit_c_mg  
0      250.0             0.0       250.0      6.3        0.0       0.0

#### 3. Running through 15 steps

In [ ]:
pl.reset()
for i in range(10):
    # Random pick
    z = np.zeros(len(pl.df))
    z[np.random.choice(range(len(pl.df)))] =1
    # stage
    s,r,d = pl.step(z)
    print('step '+ str(s))
    print('cost'+str(r))
    if d == True:
        break